### PR TITLE
Added venus-os_ngrok & text color

### PR DESCRIPTION
**Pull request by mr-manuel**
* Added: venus-os_ngrok package
* Added: Text color to `Text` items. Selected items did not change font color. It's also needed for the dark mode.

Before:
grafik
grafik

After:
grafik
grafik

* Changed: Sorted defaultPackageList alphabetically to find items easier

### CODE REVIEW

**Comment by mr-manuel** [comment]
@kwindrem please merge PR

**Comment by kwindrem** [comment]
I‘M our of town and away from my development system. I’ll check things out when I return. I’ll do the merge if everything looks OK or get back with you if there’s something I need you to address.

Thanks for all your hard work

I think it is possible to add a light/dark switch on the bar at the bottom of the screen. The only down side is there will not be a way to access it from the hard buttons

**Comment by mr-manuel** [comment]
Any updates? :-)

**Comment by kwindrem** [comment]
Sorry for the delay. I've been off on another project. I'll look it it ASAP

**Comment by kwindrem** [comment]
I have merged your changed into SetupHelper v4.41 available now. GuiMods v7.60 is also up now with your dark mode changes. Thanks for the great work. I was waiting on the v3.00 release which happened today.

**Pull request merged**
